# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "0": "debug connector",
    "1": "frame battery frame speaker",
    "2": "rear perspective view bicycle",
    "3": "signal horn projection light",
    "4": "handlebar docking station",
    "5": "electronic system architecture",
    "6": "home screen status screen",
    "7": "main system battery output",
    "8": "kickstand docking station",
    "9": "rear perspective view right bicycle system",
    "10": "kickstand docking station",
    "11": "spring moveable clamp",
    "12": "battery charger bicycle system",
    "13": "spring",
    "14": "elevation view bicycle system",
    "15": "bottom view bicycle system",
    "16": "right view bicycle system",
    "17": "series auto task",
    "18": "main system battery output",
    "19": "handlebar docking station",
    "20": "c. different home screen",
    "21": "different home screen",
    "22": "frost condition",
    "23": "co alert coloured background",
    "24": "version smartphone icon",
    "25": "user smartphone bicycle system",
    "26": "user smartphone bicycle system",
    "27": "notification list notification",
    "28": "maintenance notifications.fig",
    "29": "right hand screen output",
    "30": "current right turn indicator",
    "31": "power management system bicycle",
    "32": "sprocket pulley profile",
    "33": "bicycle system drivetrain.fig",
    "34": "possible handlebar orientation",
    "35": "orientation handlebar",
    "36": "projection lightan handlebar",
    "37": "springapp ambient temperature",
    "38": "smartphone holder",
    "39": "bicycle system infig",
    "40": "predefined home destination",
    "41": "eg red background colour",
    "42": "handlebar bicycle system",
    "43": "schematic frame speaker",
    "44": "high intensity path lighting",
    "45": "rear saddle",
    "46": "rear saddle.fig",
    "47": "left button switch",
    "48": "reduction indicator",
    "49": "reduction indicator",
    "50": "primary power storage unit",
    "51": "selectable touch screen icon",
    "52": "maintenance datum",
    "53": "central reporting server",
    "54": "configuration platform",
    "55": "rear wheel bicycle system",
    "56": "rear wheel bicycle system",
    "57": "configuration",
    "58": "configuration.fig",
    "59": "front right view upper bicycle",
    "60": "front right view detail bicycle system",
    "61": "handlebar smartphone holder",
    "62": "axi axle bicycle wheel",
    "63": "configuration infig",
    "64": "configuration infig",
    "65": "custom protective carry",
    "66": "custom protective carry",
    "67": "custom protective carry",
    "68": "external shape dock insert",
    "232": "micro secure digital high capacity",
    "1311": "gb",
    "2014": "jun",
    "2015": "dec",
    "6052": "international protection",
}
