# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "1": "view bicycle frame offig",
    "2": "perspective view bicycle frame",
    "3": "andfig",
    "4": "detail bottom bracket",
    "5": "detail bottom bracket housing",
    "6": "fastener device",
    "7": "detail bottom bracket housing",
    "12": "steel alloy suitable compound",
    "14": "battery acces hole indown tube",
    "16": "layer composite toseat tube",
    "17": "ser",
    "18": "structural strength chain",
    "19": "nov",
    "20": "additional strength durability",
    "22": "structural strength oftop tube",
    "24": "structural strength seat",
    "26": "steerer tube throughhead tube",
    "30": "bottom bracket bearing system",
    "32": "abattery acces cover",
    "34": "bottombracket bearing assembly",
    "36": "andfemale bearing cup",
    "38": "tomale bearing cup",
    "40": "pres fit thread",
    "42": "pair ofouter seal",
    "44": "response tobattery",
    "50": "wall hollow downtube shell",
    "51": "tube outsidesurface",
    "53": "tube insidesurface",
    "54": "tubesecond",
    "56": "open tobattery cavity",
    "58": "axi",
    "62": "ser",
    "70": "hollow cylindrical shapedshell",
    "74": "housing",
    "76": "bearingcavity",
    "78": "housing shelllongitudinal axi",
    "90": "optional chargingport",
    "200": "bottom bracket housing",
    "210": "anact",
    "220": "anact",
    "230": "anact",
    "386": "bb",
    "2019": "nov",
    "2020": "nov",
}
