# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "0": "adjacent thin conductive wire",
    "1": "third object present invention",
    "2": "proximal thin conductive wire",
    "3": "inspection heating plate",
    "4": "conductive pattern",
    "5": "thicknes conductive pattern",
    "6": "heating plate",
    "7": "operation conductive pattern",
    "8": "material copper nitride",
    "9": "higher volume resistivity",
    "10": "aircraft vessel space vessel",
    "11": "excellent field view passenger",
    "12": "excellent field view passenger",
    "13": "high visible transmittance",
    "14": "high visible transmittance",
    "15": "u. application ser",
    "16": "pair theconnection part",
    "17": "heating plate.fig",
    "18": "heating plate.fig",
    "19": "heating plate.fig",
    "20": "sheet substrate overhang shape",
    "21": "conductive pattern",
    "22": "pattern",
    "23": "conductive pattern",
    "24": "conventional technique.fig",
    "25": "suitable conductivity",
    "26": "visible band",
    "27": "conductive pattern offig",
    "28": "sheet",
    "29": "d)in infig",
    "30": "lower adhesive property",
    "31": "heating plate.fig",
    "32": "heating plate.fig",
    "33": "photolithographic technique",
    "34": "heating plate.fig",
    "35": "heating plate.fig",
    "36": "heating plate.fig",
    "37": "heating plate.fig",
    "38": "heating plate.fig",
    "39": "heating plate.fig",
    "40": "deterioration optical property",
    "41": "heating plate.fig",
    "42": "ferric chloride solution",
    "43": "distance davebetween center",
    "44": "rate theconnection element",
    "45": "infig",
    "46": "respective member",
    "47": "conductive pattern.fig",
    "48": "sectional shape",
    "49": "sectional shape",
    "50": "thereference pattern",
    "51": "material copper nitride",
    "52": "respective branch point",
    "53": "number openingarea",
    "54": "therespective segment",
    "55": "heating plate.fig",
    "56": "heating plate.fig",
    "57": "heating plate.fig",
    "58": "heating plate offig",
    "59": "infig",
    "60": "respective member",
    "61": "bof theconductive metal",
    "62": "sectional shape",
    "63": "pressure sensitive adhesive",
    "64": "thermoplastic resin",
    "65": "material copper nitride",
    "66": "vacuum vapor deposition",
    "67": "heating plate.fig",
    "68": "laser patterning mask",
    "69": "heating plate.fig",
    "70": "adjacent opening area",
    "71": "heating plate.fig",
    "72": "effective rate element",
    "73": "openingarea",
    "74": "rate theconnection element",
    "75": "conductive pattern.fig",
    "76": "concept trapezoidal shape",
    "77": "view sectional shape",
    "78": "heating plate.fig",
    "79": "heating plate.fig",
    "80": "adjacent opening area",
    "81": "heating plate.fig",
    "82": "respective branch point",
    "83": "number openingarea",
    "84": "therespective segment",
    "85": "heating plate.fig",
    "86": "heating plate.fig",
    "87": "heating plate.fig",
    "88": "present invention",
    "90": "transmittance",
    "95": "degree",
    "100": "examplea heating plate",
    "110": "generation beam stripe",
    "111": "excellent field view passenger",
    "112": "excellent field view passenger",
    "113": "high visible transmittance",
    "114": "high visible transmittance",
    "0115": "ji",
    "120": "sheet conductive pattern sheet",
    "125": "upper base",
    "130": "trapezoidal planar shape",
    "131": "polyvinyl butyral pvb",
    "140": "deterioration optical property",
    "141": "particular thinconductive wire",
    "143": "straight line",
    "144": "arrangement openingarea",
    "145": "non - uniform heat generation",
    "148": "speed theconductive metal",
    "149": "oxide sulfide metal material",
    "150": "suitable heat",
    "151": "ferric chloride solution",
    "152": "copper thedark film",
    "155": "widths.thereafter",
    "200": "first second embodiment",
    "210": "excellent field view passenger",
    "211": "high visible transmittance",
    "212": "high visible transmittance",
    "213": "high visible transmittance",
    "214": "high visible transmittance",
    "220": "aboveconductive pattern sheet",
    "230": "electrolytic copper foil",
    "240": "specific theconductive pattern",
    "241": "adjacent thin conductive wire",
    "245": "least theconductive metal",
    "246": "excellent field view passenger",
    "247": "excellent field view passenger",
    "248": "photolithographic technique",
    "249": "electrolytic copper foil",
    "300": "first second embodiment",
    "310": "excellent field view passenger",
    "311": "high visible transmittance",
    "312": "high visible transmittance",
    "313": "high visible transmittance",
    "314": "high visible transmittance",
    "320": "aboveconductive pattern sheet",
    "330": "electrolytic copper foil",
    "340": "fourth theconductive pattern",
    "341": "thin suitable heat generation",
    "342": "voronoi mesh pattern",
    "343": "various mesh pattern",
    "344": "aggregation number element",
    "345": "least theconductive metal",
    "346": "excellent field view passenger",
    "347": "excellent field view passenger",
    "348": "photolithographic technique",
    "349": "electrolytic copper foil",
    "380": "resin substrate",
    "384": "u. pat",
    "400": "fourth embodiment",
    "410": "excellent field view passenger",
    "411": "high visible transmittance",
    "412": "high visible transmittance",
    "413": "high visible transmittance",
    "414": "high visible transmittance",
    "420": "theconductive pattern sheet",
    "423": "thirdjoint",
    "430": "electrolytic copper foil",
    "431": "therespective surface",
    "440": "thin theconductive pattern",
    "441": "adjacent thinconductive wire",
    "442": "branch point",
    "443": "various mesh pattern",
    "445": "least theconductive metal",
    "446": "excellent field view passenger",
    "447": "excellent field view passenger",
    "448": "photolithographic technique",
    "449": "shape operation lower",
    "450": "intensity resin themetal foil",
    "460": "illustrated adark film",
    "500": "adhesive primer copper",
    "540": "enlargedconductive pattern",
    "542": "twobranch",
    "543": "defineopening area",
    "544": "theconnection element",
    "649": "u. pat",
    "1000": "thicknes",
    "2010": "third object present invention",
    "2011": "electric resistance heating wire",
    "2012": "voronoi diagram",
    "2013": "front window rear window vehicle",
    "2015": "nov",
    "2016": "jun",
    "2019": "apr",
    "4300": "pet polyethylene terephthalate film",
}
