# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "1": "fig",
    "2": "fig",
    "3": "fig",
    "4": "fig",
    "5": "fig",
    "6": "fig",
    "7": "fig",
    "8": "fig",
    "10": "thesuitcase",
    "12": "bottom",
    "14": "front side wall",
    "16": "side wall",
    "18": "top end wall",
    "20": "andbottom end wall",
    "22": "compartment",
    "24": "lid",
    "26": "zipper",
    "28": "pair spinner type wheel",
    "32": "handle",
    "34": "thesocket",
    "36": "caster",
    "38": "apocket",
    "44": "astem",
    "46": "thestrap",
    "48": "withadjustment clip",
    "52": "includesconnector",
    "54": "aflexible strap",
    "56": "top end bottom end suitcase",
    "58": "rigid orsemi - rigid reinforcement piece",
    "60": "rigid orsemi - rigid reinforcement piece",
    "487": "plath inventor u. . pat",
    "656": "example",
    "720": "example",
    "995": "plath inventor u. . pat",
}
