# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "1": "infig",
    "2": "schematic infig",
    "3": "movable platform trailer",
    "10": "recording reporting thesystem",
    "13": "feb",
    "20": "total hour thepressure vessel",
    "22": "state open closed thehatch",
    "23": "cam lock closure",
    "25": "abrasive blasting media",
    "26": "electrical pneumatic actuator",
    "30": "anindividual blast outlet",
    "40": "anoptional moisture separator",
    "42": "correspondingindividual air",
    "45": "electrical pneumatic actuator",
    "50": "ametering valve",
    "55": "throughfeed line",
    "60": "certain preferred embodiment",
    "61": "present application",
    "65": "indicative pressure level",
    "70": "acomputer processor",
    "75": "amemory",
    "80": "suitable power level type",
    "82": "separatepneumatic switch",
    "85": "square inch appropriate unit",
    "86": "thedisplay",
    "87": "remotepressurization control switch",
    "88": "pressure control valve",
    "89": "themedia sensor",
    "90": "blast outlet",
    "92": "input fromvalve sensor",
    "95": "individual display",
    "100": "individual pneumatic switch",
    "105": "total usage hour",
    "110": "button",
    "112": "desired.ahatch sensor",
    "115": "hatchstatu",
    "120": "aweather condition display",
    "125": "usingvarious weather sensor",
    "165": "amain control panel",
    "170": "aweathertight",
    "180": "andreleasable lock",
    "2012": "feb",
}
