# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "1": "front fork assembly snow bike",
    "2": "front suspension infig",
    "3": "perspective view",
    "4": "dirt bike",
    "5": "greater detail",
    "6": "cross - sectional view",
    "7": "cross - sectional view",
    "8": "cross - sectional view",
    "9": "r.",
    "10": "compressed configuration;fig",
    "11": "condition;fig",
    "12": "steering assembly",
    "14": "includinghandlebar",
    "15": "spring rate combinedsuspension",
    "18": "new snow bike front suspension",
    "20": "r. afront fender",
    "24": "feb",
    "28": "afront ski mount",
    "30": "arear suspension",
    "32": "atunnel",
    "40": "theski",
    "42": "bottom thetriple clamp",
    "44": "clamp",
    "46": "clamp",
    "48": "acenter pin",
    "49": "proper spring rate force",
    "50": "integrated unit",
    "52": "upper theplate portion",
    "54": "box shapedinner plate",
    "60": "abracket",
    "64": "clevi",
    "66": "aperture",
    "70": "engagement aperture",
    "72": "includeaperture",
    "76": "ofbracket",
    "079": "ga shock spring",
    "80": "throughaperture",
    "86": "inner portion",
    "100": "modifiedcoupler",
    "102": "asfastener",
    "110": "throughaperture",
    "120": "whereski mount",
    "122": "standingwall",
    "124": "throughaperture",
    "130": "aperture",
    "132": "sleeve",
    "134": "combination ofbushing",
    "136": "combination ofbushing",
    "138": "combination ofbushing",
    "140": "fastener",
    "142": "throughwasher",
    "150": "receivefastener",
    "160": "arubber mount",
    "170": "andbracket",
    "174": "throughaperture",
    "176": "offastener",
    "178": "throughaperture",
    "180": "throughaperture",
    "182": "offastener",
    "200": "acoupler",
    "202": "notch",
    "602": "ga shock spring",
    "738": "me patent application",
    "910": "me patent application",
    "915": "evol series",
    "2012": "publication",
    "2017": "feb",
    "9506": "scott valley",
}
