# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "1": "writer present utility model",
    "2": "structural representation",
    "3": "adjustable equivalent capacity",
    "4": "anti - skidding screw thread",
    "5": "linear switch",
    "6": "time writer present utility model;fig",
    "7": "first electromagnetic circuit",
    "8": "second first electromagnetic circuit;fig",
    "10": "structural representation",
    "20": "nib",
    "21": "onfirst circuit board",
    "30": "emission",
    "31": "andsecond circuit board",
    "32": "andfirst nib",
    "33": "regulatingdevice",
    "34": "lateral thefirst stylus part",
    "40": "display interface",
    "41": "demountable structure",
    "42": "layoutsecond circuit board",
    "43": "writer present utility model",
    "44": "lateral thesecond stylu part",
    "45": "comprisesconversion equipment",
    "331": "adjustable equivalent capacity",
    "332": "interface.above implementation",
    "333": "thisfirst switch",
    "334": "thissecond switch",
    "411": "thenib",
    "3321": "adjustable equivalent capacity",
    "3331": "first electromagnetic circuit",
    "3341": "first electromagnetic circuit",
}
