# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "1": "fig",
    "2": "fig",
    "3": "fig",
    "4": "rear",
    "5": "tofig",
    "6": "two.fig",
    "7": "fig",
    "8": "fig",
    "9": "low",
    "10": "fig",
    "11": "fig",
    "12": "fig",
    "13": "aug",
    "14": "tofig",
    "15": "tofig",
    "16": "tofig",
    "17": "fig",
    "18": "fig",
    "19": "fig",
    "20": "fig",
    "21": "tofig",
    "22": "fig",
    "23": "fig",
    "24": "fig",
    "62": "u. . provisional application",
    "90": "device",
    "100": "shoe",
    "102": "rear sole",
    "103": "ahinge",
    "104": "shoefull body",
    "105": "ashoe strap",
    "106": "ashoe body",
    "107": "shoe",
    "108": "hinge",
    "110": "theheel",
    "120": "heel",
    "130": "themid heel",
    "140": "abutton",
    "141": "button spring",
    "142": "thebutton",
    "143": "button ramp",
    "144": "abutton lock",
    "150": "theshank",
    "151": "ashank receiver",
    "160": "acompression member",
    "170": "position",
    "171": "aheel",
    "172": "aheel hinge lock",
    "173": "aheel hinge ramp",
    "2015": "aug",
}
