# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "1": "storage configuration",
    "2": "cylindrical configuration",
    "3": "elevation view scooter infig",
    "4": "accordance invention steering assembly",
    "5": "unique wide deck configuration",
    "6": "invention steering assembly",
    "7": "elevation view tricycle infig",
    "8": "accordance invention tricycle",
    "9": "low rider configuration",
    "10": "accordance exemplary invention",
    "12": "application number position",
    "14": "application number position",
    "16": "relative tobase",
    "18": "rotation rotatingmember",
    "20": "planarbottom wall",
    "22": "particular application",
    "24": "particular application",
    "26": "adjacent theend wall",
    "28": "adjacent theend wall",
    "29": "wide range scooter design",
    "32": "theupper",
    "34": "flush thearcuate",
    "36": "withincavity",
    "38": "theside wall",
    "40": "bin theend wall",
    "42": "theend wall",
    "46": "same cross - sectional shape",
    "48": "accordance invention",
    "50": "cylindrical configuration",
    "52": "therebetween",
    "54": "theshoulder",
    "56": "pressingpush button",
    "58": "fromcentral aperture",
    "60": "fromcentral aperture",
    "61": "various tricycle design",
    "62": "least outer ofcover plate",
    "64": "least outer ofcover plate",
    "66": "threadedbore",
    "70": "throughcentral aperture",
    "72": "solid wall blind bore",
    "74": "locking mechanism",
    "76": "particular application",
    "78": "bia ofspring",
    "80": "aninner",
    "82": "anouter",
    "84": "surface",
    "86": "theinner wall",
    "100": "second thescooter",
    "102": "thefirst frame",
    "104": "provided.thesecond frame",
    "106": "generallyelongate support",
    "110": "thesecond",
    "112": "arear wheel",
    "114": "platform ordeck",
    "116": "embodiment",
    "118": "ato lock thesteering assembly",
    "120": "thehead tube",
    "122": "brace orarm",
    "124": "tohandlebar stem",
    "126": "configuration",
    "128": "afork",
    "130": "thefront wheel",
    "132": "afork stem",
    "136": "upper andlower bearing",
    "138": "upper andlower bearing",
    "150": "structure operation ofscooter",
    "210": "desirable fortricycle",
    "212": "thefront frame",
    "214": "wide variety shape design",
    "216": "therear frame",
    "218": "thefront fork",
    "220": "rotation ofhandlebar",
    "222": "thefork stem",
    "224": "apart fork orleg",
    "226": "rotation thefront wheel",
    "228": "afront axle",
    "230": "pair ofpedal",
    "232": "ahandlebar stem",
    "234": "pair ofhandle",
    "236": "thehead tube",
    "238": "frame support element",
    "240": "positionedadjacent knuckle",
    "244": "asaddle",
    "246": "themiddle",
    "248": "endportion",
    "252": "rotation therear wheel",
    "2009": "mar",
}
