# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "1": "non - insulated compartment",
    "2": "pocket created.fig",
    "3": "closing compartment",
    "4": "non - insulated compartment",
    "5": "non - insulated compartment",
    "6": "infig",
    "7": "infig",
    "8": "non - insulated compartment",
    "9": "non - insulated compartment",
    "10": "non - insulated compartment",
    "31": "united state patent trademark office",
    "35": "noticethe present application non - provisional utility application",
    "62": "prior provisional application",
    "100": "present invention",
    "110": "flexible main bodyouter",
    "112": "front bag",
    "113": "non - insulated surface",
    "114": "lowerfront",
    "120": "present invention",
    "130": "present invention",
    "150": "main compartmentinterior lining",
    "160": "alaptop pocket",
    "161": "pen pocket",
    "162": "bottle pocket",
    "163": "aphone pocket",
    "164": "credit card",
    "165": "alarge pocket",
    "166": "asmall pocket",
    "167": "akey clip",
    "200": "rigid insulatedcompartment",
    "201": "insulatedupper",
    "202": "insulatedlower",
    "203": "insulatedlateral",
    "205": "insulated anterior",
    "206": "insulatedposterior",
    "250": "insulatedcompartment flap",
    "300": "content fixednon compartment",
    "301": "insulatedupper",
    "306": "non - insulated posterior",
    "350": "andnon compartment flap",
    "400": "thefront pocket",
    "500": "entirety upper abase",
    "501": "thefront",
    "502": "backedge",
    "504": "andsecond",
    "600": "optional accessory",
    "610": "adetachable shoulder strap",
    "611": "shoulder strap ring",
    "620": "azipper",
    "630": "alock",
    "640": "andmetal foot",
    "650": "tag",
    "660": "closing compartment",
    "1001": "rearward interior view",
    "2002": "overall frontal view",
    "2017": "united state patent trademark office",
    "3003": "overall frontal view",
}
