# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "1": "non - motorized configuration",
    "2": "non - motorized configuration",
    "3": "rear fork",
    "4": "conventional bicycle procedure",
    "5": "bottom mainframe leftportion",
    "6": "shaft drive mechanism.fig",
    "007": "coast bike.further",
    "7": "configuration;fig",
    "8": "coast bike.further",
    "9": "mainframeright",
    "10": "conventional bicycle procedure",
    "11": "conventional attachment device",
    "12": "conventional bicycle procedure",
    "13": "schematic diagram infig",
    "14": "battery mount assembly offig",
    "15": "mainframe assembly convertible",
    "16": "application continuation u. patent application ser",
    "17": "mainframe assembly convertible",
    "18": "slim nature convertible bike",
    "19": "battery mount assembly",
    "20": "similar toseat",
    "21": "purpose thechain",
    "23": "preset motor performance.fig",
    "24": "convertible bike",
    "25": "theexternal battery",
    "26": "gp navigation device",
    "27": "theexternal battery mount",
    "28": "footrest",
    "29": "andfig",
    "36": "similar todrivetrain assembly",
    "41": "theelectronic control assembly",
    "44": "attachedfreewheel sprocket",
    "45": "thethrottle sensor",
    "46": "footrest similar tofootrest",
    "49": "electronic controlhousing",
    "50": "thedrivetrain",
    "51": "internalbattery",
    "62": "u. provisional patent application",
    "80": "foot",
    "81": "angledrear",
    "84": "exterior themainframe assembly",
    "90": "non - motorized configuration",
    "92": "theelectric cable",
    "95": "conventional bicycle axle hardware nut",
    "96": "andelectric cable",
    "100": "thesprocket",
    "102": "theelectrical motor",
    "104": "additional feature",
    "106": "electronic speed control",
    "108": "optional external direct connect orwireles device",
    "110": "efficient mainframe ease",
    "112": "leftportion",
    "116": "asteering tube",
    "118": "thedown tube",
    "120": "theplate",
    "122": "andseat tube",
    "124": "thedrivetrain assembly mount",
    "160": "efficient mainframe ease",
    "162": "leftportion",
    "166": "asteering tube",
    "168": "drivetrainassembly mount component",
    "170": "andseat tube",
    "172": "theplate",
    "180": "theexternal battery mount",
    "182": "thebattery",
    "183": "esc",
    "186": "thedrivetrain assembly",
    "188": "viacable",
    "192": "theelectric cable",
    "201": "better sound transmission",
    "203": "theleft grip",
    "204": "corresponding size",
    "205": "adjacent aright grip",
    "207": "handlebar",
    "210": "speaker sound exciter inducer",
    "212": "thenumber plate",
    "215": "sound system",
    "218": "panel",
    "220": "drivetrain.while rider",
    "223": "agp device",
    "226": "front thefootrest",
    "227": "amainframe assembly",
    "229": "withfastener",
    "230": "frontangled portion",
    "232": "rear right angledportion",
    "235": "rear angledportion",
    "414": "coast bike.further",
    "584": "u. pat",
    "654": "u. pat",
    "730": "u. pat",
    "794": "u. pat",
    "2010": "low seat narrow foot platform",
    "2014": "u. patent publication",
    "2015": "sep",
    "2018": "aug",
}
