# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "0000": "e.g",
    "1": "fig",
    "2": "e.g",
    "3": "fig",
    "4": "fig",
    "5": "fig",
    "10": "control",
    "12": "opening",
    "14": "example",
    "15": "way",
    "16": "thebutton",
    "18": "ofbutton",
    "20": "ofbutton",
    "22": "button",
    "24": "pres button",
    "26": "ofbutton",
    "28": "ofbutton",
    "30": "pres button",
    "32": "device",
    "33": "asound system",
    "34": "case",
    "35": "adock",
    "36": "signal",
    "38": "example",
    "40": "signal",
    "42": "speaker",
    "44": "opening",
    "46": "amicrophone",
    "48": "pin connector",
    "50": "battery orbattery",
    "52": "thedevice",
    "54": "example",
    "56": "thedevice",
    "58": "insulatedelectrical wire",
    "350": "lake washington blvd",
    "9803": "kirkland",
}
