# Patent Number Descriptions
# Generated automatically from patent text

number_descriptions = {
    "000": "touch compatible display",
    "0": "matching algorithm",
    "1": "vehicle type trike motorcycle",
    "2": "measure angle theplastic shell",
    "3": "cellular network technology",
    "4": "insecure communication channel",
    "5": "medium speed",
    "6": "corresponding surface",
    "7": "fig",
    "8": "corresponding surface",
    "10": "first funnel shapedportion",
    "11": "fig",
    "12": "compressive force",
    "13": "view",
    "14": "tensile force",
    "16": "second funnel shapedportion",
    "18": "rich graphical user interface",
    "19": "fig",
    "20": "second wheel casing",
    "22": "third cell cluster bm module",
    "24": "internal temperature sensor",
    "25": "additional usable space",
    "26": "thesensor",
    "28": "limited number option",
    "30": "right hand drive",
    "32": "view theleft control interface",
    "34": "subset available datum",
    "35": "second system driver passenger subsystem",
    "36": "right speaker",
    "40": "illustrated thefirst wheel",
    "42": "conventional metal inner frame",
    "44": "comprisesshock absorber",
    "46": "therear spring",
    "47": "short load path",
    "48": "theconnector",
    "50": "support surface",
    "52": "circumference thebase plate",
    "54": "edge",
    "56": "least shape additional rib",
    "58": "housing",
    "60": "different solution",
    "62": "weight rear swingarm",
    "64": "motor housing",
    "66": "reliable drive arrangement",
    "68": "belt guard",
    "70": "thedrive belt",
    "72": "thepulley",
    "80": "rotation thefront wheel",
    "82": "thefront wheel suspension",
    "84": "spring theshock absorber",
    "86": "first connector",
    "88": "support surface",
    "92": "second connector",
    "94": "thesecond support",
    "98": "thevehicle head tube",
    "100": "hollow tube",
    "102": "plate",
    "106": "theinner tube",
    "108": "upward force",
    "114": "larger heat larger heat sink",
    "116": "configuration thebattery pack",
    "118": "total number ofbattery module",
    "120": "central vehicle)controller",
    "121": "power transfer cable",
    "122": "possibility vehicle",
    "123": "bottom seat scooter vehicle",
    "124": "aconnection",
    "125": "aparticular lock pin",
    "126": "locking mechanism",
    "127": "particular material",
    "128": "vehicle drivetrain",
    "129": "driver orientedcamera",
    "130": "conjunction internet system",
    "131": "thehorizontal speaker",
    "132": "particular acoustic intensity",
    "133": "pedestrian traffic user",
    "134": "horizontal array speaker driver",
    "151": "parking scooter",
    "152": "additional alternative",
    "153": "asteering angle sensor",
    "154": "ambient noise wind road noise",
    "155": "accelerometer gyroscope sensor",
    "170": "insecure communication channel",
    "171": "legal test requirement",
    "172": "theuser interface controller",
    "173": "communication bu",
    "174": "display scooter characteristic",
    "175": "video andtouch communication bu",
    "176": "essential scooter function",
    "177": "communication bu",
    "178": "various location vehicle",
    "179": "number thesecommunication bus",
    "180": "remote control system",
    "181": "physical thecommunication",
    "182": "thesingle cover plate",
    "183": "byoptical adhesive",
    "185": "compatible radio element",
    "187": "thecomputing device",
    "188": "dedicateddigital communication",
    "189": "theradio transceiver",
    "190": "theantenna",
    "191": "communication bu",
    "192": "single package",
    "193": "dedicatedcommunication bu",
    "194": "theradio transceiver",
    "195": "anantenna",
    "196": "controllingvehicle",
    "197": "thecentral controller",
    "198": "communication bu",
    "199": "rf",
    "200": "schematic anexemplary battery pack",
    "201": "module",
    "202": "cell cluster",
    "203": "cell",
    "250": "insecure communication channel",
    "384": "touch compatible display",
    "800": "better quality display",
}
